name: release_to_trigger
description: "Capture swipe gestures to trigger actions with customizable progress indicators, smooth animations, and haptic feedback. Great for pull-to-refresh UIs."
version: 1.0.4
homepage: https://github.com/tejaspalyekar/release_to_trigger
repository: https://github.com/tejaspalyekar/release_to_trigger
issue_tracker: https://github.com/tejaspalyekar/release_to_trigger/issues
documentation: https://github.com/tejaspalyekar/release_to_trigger/blob/main/README.md
license: MIT
topics:
  - pull-to-refresh
  - gesture-detection
  - interactive-ui
  - flutter-widgets
  - animations
  
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pedantic: ^1.11.1
  test: ^1.24.9
  mockito: ^5.4.4

