name: release_to_trigger
description: "release_to_trigger is a Flutter package for capturing vertical swipes and triggering actions, perfect for custom triggers like loading new content or activating app features"
version: 1.0.1
homepage: https://github.com/tejaspalyekar/release_to_trigger
repository: https://github.com/tejaspalyekar/release_to_trigger
license: MIT
topics:
  - pull-to-access
  - pull-to-refresh
  - pull-to-reveal
  - trigger-actions
  - swipe-to-access
  
  
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

